DROP TABLE IF EXISTS posts;

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_name TEXT NOT NULL,
    event_description TEXT NOT NULL
);